#!/usr/bin/env node
// Reads .env and generates server/baked-env.ts with all values compiled in.
// Run before tsc so the server binary needs no .env file at runtime.

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env');

let raw = '';
try {
  raw = readFileSync(envPath, 'utf8');
} catch {
  console.warn('⚠  No .env file found — writing empty baked-env.ts (server will use process.env)');
  writeFileSync(
    resolve(root, 'server/baked-env.ts'),
    '// AUTO-GENERATED by scripts/bake-config.mjs\nexport const BAKED_ENV: Record<string, string> = {};\n',
    'utf8'
  );
  process.exit(0);
}

const env = {};
for (const line of raw.split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eq = trimmed.indexOf('=');
  if (eq < 0) continue;
  const key = trimmed.slice(0, eq).trim();
  // Strip surrounding quotes if present
  let val = trimmed.slice(eq + 1).trim();
  if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
    val = val.slice(1, -1);
  }
  env[key] = val;
}

const lines = Object.entries(env)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join('\n');

const output = [
  '// AUTO-GENERATED by scripts/bake-config.mjs — contains secrets, never commit',
  '// Re-run `node scripts/bake-config.mjs` after editing .env',
  'export const BAKED_ENV: Record<string, string> = {',
  lines,
  '};',
  '',
].join('\n');

writeFileSync(resolve(root, 'server/baked-env.ts'), output, 'utf8');
console.log(`✓ server/baked-env.ts generated (${Object.keys(env).length} vars)`);
